list: $/diz/photos/models/photos/columns.yaml
modelClass: Diz\Photos\Models\Photos
title: Photos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diz/photos/photos/update/:id'
